name: Install TA-Lib
description: Build & install TA-Lib 0.6.4 from source

runs:
  using: composite
  steps:
    - name: Install system build deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl gcc make build-essential ca-certificates

    - name: Download TA-Lib source
      shell: bash
      run: |
        curl -LO https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-src.tar.gz
        tar xzf ta-lib-0.6.4-src.tar.gz

    - name: Build & install TA-Lib
      shell: bash
      run: |
        cd ta-lib-0.6.4
        ./configure --prefix=/usr
        make
        sudo make install
